### ISSUE TITLE
Clean data from pen tester

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1106]
**Summary**
The pentester did do a lot of downloads and made our data wonky

**User story**
The user story that has led to the need for this task, expressed in the format below.
_As a product manager
_I would like to be able to trust the data
_so that I can report accurately

**Outcome/deliverable**
Amended charts in Looker

**Deadline**
this sprint

**Links**
https://lookerstudio.google.com/u/0/reporting/dfa5a2b1-dc20-4718-9dfa-a38b5fa8568c/page/p_0frmm2yegd/edit

**Reviewer**
@faucomte97 @SKairinos 

**People to contact**
@lauracumming

**Comment by faucomte97** [comment]
Specifically for the coding club packs endpoints, we could:
a) add a check for the testing header to ensure we do not increment the data or
b) get rid of the endpoint which we'd wanted to do for a while. Enable the file download on the frontend, and instead of tracking the data through the DB, track it with GTM (would be less accurate data because of cookies). We then need to figure out how to filter out the testing clicks using the header within GTM. A quick investigation on GTM did not reveal a way to trigger depending on HTML headers so we'd need a PoC before we choose this option

A separate note on all this:

Our own accounts as well as the pen tester's accounts should be marked as "staff" going forward so we can use this flag to filter out data tracking and other analytics across the site. NOTE: This only affects authenticated requests.
This does not solve the issue of the club packs downloads as this can be done anonymously.

**Comment by SKairinos** [comment]
I vote option B. In the long run, this is the full fix. I don't believe we should be using our API to track our site's usage - this is what Google Analytics and Tag Manager is for.

In addition, you **can** track users' data even if they reject cookies [so long as the data we record is anonymous](https://www.ucl.ac.uk/data-protection/guidance-staff-students-and-researchers/practical-data-protection-guidance-notices/anonymisation-and#:~:text=information%20which%20does%20not%20relate,not%20apply%20to%20anonymised%20information). As always, for safety, we should double check with a lawyer versed in GDPR. Consenting to cookies just means we can track that person **individually** - which is generally used for personalised ads. So we'll still be able to track how many times the "download club pack" button was clicked.

Regarding how to differentiate if a staff or non-staff user has triggered an event _before_ they sign in, what we could do is ask the pen tester to set the following key-value pair in their local storage **is-staff=1**. Then, we set these values in the [data layer](https://developers.google.com/tag-platform/tag-manager/datalayer) and send it as an [event parameter](https://developers.google.com/analytics/devguides/collection/ga4/event-parameters?client_type=gtm). Then we can filter out all events where **is-staff=1**.

**Comment by SKairinos** [comment]
Correction: we can avoid triggering the event altogether where **is-staff=1**

**Comment by faucomte97** [comment]
@lauracumming Let me know what you think of the above

**Comment by SKairinos** [comment]
@lauracumming, reminder of the above

**Comment by lauracumming** [comment]
Agreed re asking pentester to add: is-staff=1

It also sounds sensible to track the usage through tag manager as I imagine we will currently be missing visitor (not signed in) interactions with our current method. 

It is all anonymous through GA4 as we don't track.

**Comment by faucomte97** [comment]
Just clarifying that our current method includes tracking for all users, whether they are logged in or not.

**Comment by faucomte97** [comment]
Follow up tasks:
- Ensure the next pen testers use is-staff=1 and use that flag - can be applied to our test accounts too.
- #1141
