### ISSUE TITLE
Add GA (Dotdigital tables) to Looker studio

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1111]
Add GA Email and Social media sources to Looker studio in order to see:

- [ ] Email campaign links to visiting website
- [ ] Social media campaigns links to visiting website
- [ ] Gitbook links from social media and emails to website

**Comment by evemartin** [comment]
I have added some charts to pages 2 ([CFL Engagement](https://lookerstudio.google.com/reporting/dfa5a2b1-dc20-4718-9dfa-a38b5fa8568c/page/p_o5f7l1spsc)) and 3 ([CFL Engagement - traffic sources](https://lookerstudio.google.com/reporting/dfa5a2b1-dc20-4718-9dfa-a38b5fa8568c/page/p_0frmm2yegd)) that display data on the users referred to the CFL website and events on the website caused by our named campaigns! The reason why they're spread across two pages is just because there wasn't enough space on one page for everything - please let me know if there's anything I'm missing or that I've misunderstood and I can add/modify the charts :)
