### ISSUE TITLE
Email copy change for student

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1126]
**Summary**
When the student is released from a class and receives an email, it only tells them to verify their account (standard verification email)

**User story**
_As a student
_I would like to understand what I need to do and why I have received the email from Code For Life
_so that i can verify if I choose to and carry on with Rapid Router independently

**Outcome/deliverable**
Copy for new email

**Deadline**
This sprint

**Reviewer**
@faucomte97 

**People to contact**
@lauracumming

**Comment by SKairinos** [comment]
When a student is released from a school, they will get an email with the following copy.

"""
You have been released from the school {school_name_here} by {teacher_full_name_here}. This means your account is no longer managed by your teacher and you've been converted from a student to an independent user.

Your password remains the same but you'll need to verify you own this email address first.
(VERIFY BUTTON HERE)

If you believe a mistake has been made, please inform the teacher at {teacher_email_here}.
"""

@lauracumming, do you approve of the above copy?

**Comment by lauracumming** [comment]
I'd like @faucomte97 to comment on that last sentence as we may not be able to disclose the teacher email as it's personal data.

**Comment by faucomte97** [comment]
Both the teacher's name and email address are personal data.

In the case where the student was released by their own teacher, then the student would already know the teacher's name, and most likely their email address too, so we wouldn't be disclosing new information to the student, as such.
However, in the case where the student was released by another teacher than their own, then they might not know that teacher's personal data, so disclosing that to the student could be seen as problematic.

If we want to mitigate this, we could just say "you've been released from the school {school_name}." and "please inform your teacher" as they would still know how to get in touch with their own teacher who could then contact the admin. It's less informative I know, but less risky too.
We could also potentially make it so that the less informative version gets sent out only if the releasing is done by a teacher other than the direct teacher - but it probably would be too much trouble for what it's worth.

**Comment by SKairinos** [comment]
"""
You have been released from the school {school_name_here}. This means your account is no longer managed by your teacher and you've been converted from a student to an independent user.

Your password remains the same but you'll need to verify you own this email address first.
(VERIFY BUTTON HERE)

If you believe a mistake has been made, please reach out to the school.
"""

**Comment by SKairinos** [comment]
@lauracumming and @faucomte97 , how about now?

**Comment by faucomte97** [comment]
yes

**Comment by faucomte97** [comment]
approved
