### ISSUE TITLE
Data task - separate out active returning users

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1157]
**Summary**
We would like to understand the number of users that register, verify but then never come back. 
Therefore we need to separate out 'active returning' from 'active users' so we can see if they actually use the products.

**User story**
The user story that has led to the need for this task, expressed in the format below.
_As a product manager
_I would like to see what percentage of verified users actually use the product
_so that I can understand if we need to introduce more emails to encourage activity

**Outcome/deliverable**
Data displaying the total number of returning users vs total non-returning/verified users, by year

**Deadline**
This sprint

**People to contact**
@lauracumming

**Comment by evemartin** [comment]
Update before I go on holiday: added to the Stakeholder Report! Instead of creating a completely new chart for this, I just added a breakdown dimension to the existing cumulative active/verified users chart, since they're very similar so there's a lot of overlap. Feel free to separate them out again though, the only difference is that the old one didn't have a breakdown dimension and this new one does!

**Comment by lauracumming** [comment]
Thanks Eve, happy to close this task. Looks like the number is going down, so that is good. 👍
