### ISSUE TITLE
Organise Python Den resources

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1177]
**Summary**
Organise Python Den resources for release. We need to check spaces and ensure students and teachers can access what they need.

**User story**
_As a user
_I would like to find the resources I need 
_so that I am able to follow the Python Den sessions 

**Outcome/deliverable**
**Students** - access to worksheets
**Independents** - access to videos and worksheets
**Teachers** - access to videos, slides and worksheets

**Deadline**
This sprint

**Reviewer**
@faucomte97 

**People to contact**
@lauracumming @rdcruzCFL

**Comment by rdcruzCFL** [comment]
These issues need to be resolved as part of this ticket:
**Rapid Router Resources:**

- [x] Python guide formatting needs correcting

**Python Den**
- [x] Update the session order in https://code-for-life.gitbook.io/independent-student-resources/python-den-resources-beta/learning-to-program-using-python
- [x] Add a link to the Raspberry Pi Code editor at the top of this page https://code-for-life.gitbook.io/independent-student-resources/session-1-output-operators-and-data and there's an extraneous / in the Python in Activity 1
- [x] Include the docx and pdf versions of the worksheets
- [x] Check worksheets for missing screenshots, e.g. Activity 1 on Session 3

**Comment by lauracumming** [comment]
@faucomte97 Can you please check these in as not sure about the unchecked Python Guide comment. Check [student](https://code-for-life.gitbook.io/student-resources/), [independent](https://code-for-life.gitbook.io/independent-student-resources/) and Teacher

**Comment by lauracumming** [comment]
Ready for review. @evemartin  links should be available now for levels page

**Comment by evemartin** [comment]
Hi @lauracumming, just a few small things I've noticed so far while going through the resources:
- it looks like the [Worksheet 6 page](https://code-for-life.gitbook.io/student-resources/python-den-student-resources/worksheet-6-iteration-part-2) includes the wrong worksheet pdf
- I was wondering what episode Iteration Pt. 2 corresponds to? I'm assuming Iteration Pt. 1 corresponds to "Counted Loops Using While" but wasn't sure about part 2!
- it looks like the independent student pages for [Worksheet 2](https://code-for-life.gitbook.io/independent-student-resources/python-den-resources-beta/session-2-variables-input-and-casting) and Worksheets 7-11 don't have a link to a youtube video, is that intentional?

**Comment by lauracumming** [comment]
Thanks @evemartin I still need to edit some videos and upload them but I'll check the other bits you mentioned. 👍

**Comment by faucomte97** [comment]
@lauracumming I don't understand what the unchecked requirement points to, the Introduction to Python docs don't have any blocks in them, since it's all Python.

**Comment by rdcruzCFL** [comment]
- [ ] This could do with a complete rewrite! https://code-for-life.gitbook.io/independent-student-resources/rapid-router-resources/introduction-to-python

**Comment by rdcruzCFL** [comment]
@lauracumming @faucomte97  I couldn't find that repeat-until either, it must have been deleted. I have removed the point.

**Comment by lauracumming** [comment]
Completed
