### ISSUE TITLE
Remove any connections to UA and replace with GA4

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1201]
We need to remove old connections and replace with GA4 as there are still connections in the CFL reports.

![Image](https://github.com/user-attachments/assets/698482bf-243e-4e13-81c8-8e9e83d82d44)

**Comment by evemartin** [comment]
I checked the report and found that one chart had a broken connection (the one on page 4 about login methods) - I have fixed it but I'm not sure it was broken because of UA because it refers to tables whose charts have connections that are still working, and I can't find any data sources that are directly linked to UA instead of GA4. I looked up the warning about switching to GA4 and apparently it was displaying for all users regardless of whether or not they were using UA or GA4, so it's possible that there's actually no issue with our report even though it's being displayed. I'd suggest downloading the report now though just in case other charts need to be fixed in the future!
