### ISSUE TITLE
Handover to team

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1206]
Sadly, we will be saying goodbye to the lovely Eve as she moves to her next rotation. 

This is a reminder to write up and handover anything that needs to be handed over before you go. 😔

**Comment by evemartin** [comment]
Looker:
- because the report is owned by Laura, all the charts should be safe - the only potential risk is losing access to the data sources, but since Laura is the owner of all the tables in BigQuery (see below section on BigQuery) I don't expect this to be an issue
- I did notice when I checked Looker that there were a few charts with a broken connection - I checked and it was because something had gone wrong with some of the reusable data sources in the report that were created by Clotilde Freeman, I think because she has left Ocado now. The charts should all be fixed now but in case this comes up again in the future all you need to do to fix it is create a new data source linking to the same BigQuery table/resource and replace it in the broken charts

BigQuery: 
- all the tables in `cfl_prod_copy` are owned by Laura via an inherited role
- I have shared a bunch of unscheduled (and as far as I know not directly used) queries with Laura as owner as well - these are the queries in the `Queries` and `(Classic) Queries (15)` folders! I don't think these are directly connected to the scheduled queries anymore but I originally used them to draft the scheduled queries and do some general investigation/exploration
- the scheduled queries will need to be transferred by @lauracumming - this can be done for each scheduled query by taking the following steps:

1. Go to the scheduled query from the "Scheduled queries" tab on BigQuery and click on the "Configuration" tab

![Image](https://github.com/user-attachments/assets/453a76e8-f6c8-4479-ae13-627d98694672)

2. Click on "Update credentials" on the far right of the "User" row and log in with the appropriate account when prompted - you will have to click "Allow" to give the BigQuery Data Transfer Service permission to complete the transfer
3. You should get this message to show that the transfer was successful, and when you reload the page it should show your email in the "User" row


![Image](https://github.com/user-attachments/assets/b339cb97-4328-4e87-b21d-947b8736d4f9)

**Comment by lauracumming** [comment]
Done
