### ISSUE TITLE
Create templates for boards

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#768]
We need to create some templates for use on the Admin and UX boards.

They need to suit the kinds of tasks we do, so it would be a good idea to read through some of the previous tasks and design based on them. UX has research and design based tasks so they should be split that way. 

- [x] Admin board templates
- [x] UX borad templates
- [ ] 
[Miro board](https://miro.com/app/board/uXjVNRAAeW4=/)

**Comment by SKairinos** [comment]
[Here's guidance on how to create templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by andrewmales** [comment]
I've been looking at a simple template for admin boards. I suggest a single, generic template for admin, rather than lots of different ones that would need to be maintained and might be confusing to know what to select. Of course, if after implementation we think this isn't proving to be of benefit, then we can always change it and/or add other templates. Let's start simple, though.

Suggestion:

Summary
User story: As a…I would like…so that…
Outcome/deliverable
Deadline
Links
Reviewer
People to contact

Example:
**Summary**
Create templates for the Admin and UX boards.

**User Story**
As a C4L team member
I would like some GitHub templates created for Admin and UX tasks
so that tasks are created with consistency and with enough structured information so that anyone can pick them up and understand what is needed to complete the task.

**Outcome/Deliverable**
One or more GitHub templates that can be selected when adding an Admin or UX task in GitHub.

**Deadline**
None, but would be nice by 31/03/24.

**Links**
[Previous analysis in Miro](https://miro.com/app/board/uXjVNRAAeW4=/).

**Reviewer**
Laura Cumming

**People to Contact**
Laura Cumming

**Comment by lauracumming** [comment]
This looks like a good template for Admin, Research and Design. 
Is that what you are thinking @andrewmales ?

**Comment by andrewmales** [comment]
Yes - at least for the admin board. I'll look at the codeforlife-design board to see if also fits for that or whether to have slightly different ones. I'll look at implementing the admin template now.

**Comment by andymales2** [comment]
New Admin template added.
[here](https://github.com/ocadotechnology/codeforlife-admin/issues/new/choose)

![Screenshot 2024-03-28 at 13 47 19](https://github.com/ocadotechnology/codeforlife-admin/assets/162485746/18861fbf-90c9-4e76-99c7-c100235e2ae5)

**Comment by lauracumming** [comment]
Brill

**Comment by andymales2** [comment]
New template added for the design repo.
[here](https://github.com/ocadotechnology/codeforlife-design/issues/new/choose)
<img width="785" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0JHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1250b82b2180e7b61bca1d6f1bd50330e93083ed/Screenshot%202024-04-09%20at%2015.29.01.png" alt="Screenshot 2024-04-09 at 15.29.01.png" />

**Comment by lauracumming** [comment]
Great, thanks @andrewmales, we will road test this too. Looks good. 👍
