### ISSUE TITLE
Investigate formal acceptance for external contributors

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#863]
We need to create a way for external contributors to accept the licensing agreement, preferably on Gitbook, or adding a sentence to when they raise a pull request.

**Comment by faucomte97** [comment]
My initial idea was to have two workflows, one responsible for figuring out if the PR's creator was part of the codeforlife team in the OT org, and another one responsible for capturing the volunteer's consent of the contributor agreement.

- For the first workflow, this branch has some work done towards it already: https://github.com/ocadotechnology/codeforlife-portal/tree/test_contributor_action. It successfully detects if the creator of the PR belongs to the codeforlife team. It then has an if statement which should be used to trigger the second workflow.
- The tricky bit comes with the second workflow. Originally I was hoping that the workflow would require a manual trigger in order to run, so that the volunteer would have to manually click a button to "accept" the contributor agreement. The workflow itself would simply notify us (potentially) that the volunteer has accepted the agreement, and that the PR is ready to be merged in. It could notify us about this in #codeforlife-alerts just like the appengine repo does in the deployment workflow.
- The tricky bit is to figure out how to include a manual trigger. The idea is that: volunteer raises a PR -> first workflow detects that the volunteer isn't a member of codeforlife -> first workflow triggers the second workflow -> the second workflow is queued but doesn't proceed unless the volunteer manually launches it.
- An example of this "manual trigger" is found when deploying to production in the appengine repo. However, this setting is a protection rule on the branch-level, not on the PR level. As such, some more investigation needs to be done to figure out how to queue a workflow and continue it upon manual input submitted only by the volunteer themselves, all that in a workflow working on the PR level, not the branch level.
- Finally, we would need to amend the PR templates so that it includes instructions on 1) why there is a queued workflow waiting for the volunteer's approval 2) where to find it and run it 3) what it means to accept it - ie that the volunteer has read and accepted the contributor agreement (add in a link to the agreement in the template).
