### ISSUE TITLE
Data task - investigate parameters in Big Query

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#901]
We need to understand how we can implement more flexible time based data in Big Query so that when we pull it into Looker Studio it has the options in place.

**Comment by SKairinos** [comment]
Relevant documentation:
[Running parameterized queries with BigQuery](https://cloud.google.com/bigquery/docs/parameterized-queries)
[Use parameters in a custom query in Looker Studio](https://support.google.com/looker-studio/answer/10588439?hl=en)

**Comment by SKairinos** [comment]
Parameterised queries are possible both in BigQuery and Looker Studio.

I created the following query that retrieves the all the schools in a specific country, where the country is a parameter.

`SELECT * FROM cfl_prod_copy.common_school WHERE country=@country`

Parameterised queries cannot be scheduled in BigQuery since they don't contain static values. They can only be executed on demand via a client package or using the `bg query` command line.

The more useful case for us being able to dynamically generate reports in Looker Studio. To do so:

1. Go to Looker Studio.
2. Add BigQuery as a data source.[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemFJQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--468c48caf1badd74836de7d73c48a43a78fbfd56/image.png)

3.
